function [textValue, color, valid] = ...
        recognition_status_text(status, acceptedRateHz)
%RECOGNITION_STATUS_TEXT Format one strict English recognition status line.

textValue = "Recognition Status: RECOGNITION UNAVAILABLE";
color = [0.8, 0.1, 0.1];
valid = false;
if ~isValidRate(acceptedRateHz) || ~isValidStatus(status)
    return;
end
valid = true;
if ~status.available
    return;
end

switch string(status.display_state)
    case "WARMING_UP"
        textValue = "Recognition Status: WARMING UP";
        color = [0.35, 0.35, 0.35];
    case "TRANSITION_UNSTABLE"
        textValue = "Recognition Status: TRANSITION / UNSTABLE";
        color = [0.85, 0.55, 0.1];
    otherwise
        gesture = replace(string(status.display_state), "_", " ");
        textValue = sprintf([ ...
            'Recognized Gesture: %s | Confidence: %.1f%% | ' ...
            'Inference Rate: %.1f Hz | GPU Latency: %.1f ms'], ...
            gesture, 100 * status.confidence, acceptedRateHz, ...
            status.inference_ms);
        textValue = string(textValue);
        color = [0.1, 0.6, 0.2];
end
end

function valid = isValidRate(value)
valid = isa(value, "double") && isscalar(value) && isreal(value) && ...
    isfinite(value) && value >= 0;
end

function valid = isValidStatus(value)
expectedFields = ["available", "display_state", ...
    "candidate_gesture_id", "confidence", "probabilities", ...
    "inference_ms", "round_trip_ms", "sequence", "sensor_time_s"];
valid = isstruct(value) && isscalar(value) && ...
    isequal(sort(string(fieldnames(value))), sort(expectedFields.')) && ...
    islogical(value.available) && isscalar(value.available);
if ~valid
    return;
end
if value.available
    valid = isAvailableStatus(value);
else
    valid = isUnavailableStatus(value);
end
end

function valid = isAvailableStatus(value)
labels = recognitionClassLabels();
displayStates = [labels, "WARMING_UP", "TRANSITION_UNSTABLE"];
probabilities = value.probabilities;
valid = isTextMember(value.display_state, displayStates) && ...
    isTextMember(value.candidate_gesture_id, labels) && ...
    isBoundedDouble(value.confidence, 0, 1) && ...
    isa(probabilities, "double") && isrow(probabilities) && ...
    numel(probabilities) == 8 && all(isfinite(probabilities)) && ...
    all(probabilities >= 0 & probabilities <= 1) && ...
    abs(sum(probabilities) - 1) <= 1e-4 && ...
    isBoundedDouble(value.inference_ms, 0, Inf) && ...
    isBoundedDouble(value.round_trip_ms, 0, Inf) && ...
    isa(value.sequence, "uint64") && isscalar(value.sequence) && ...
    isa(value.sensor_time_s, "double") && ...
    isscalar(value.sensor_time_s) && isreal(value.sensor_time_s) && ...
    isfinite(value.sensor_time_s);
if valid && ismember(string(value.display_state), labels)
    valid = string(value.display_state) == ...
        string(value.candidate_gesture_id);
end
end

function valid = isUnavailableStatus(value)
valid = isExactText(value.display_state, "RECOGNITION_UNAVAILABLE") && ...
    isExactText(value.candidate_gesture_id, "") && ...
    isa(value.confidence, "double") && isscalar(value.confidence) && ...
    isnan(value.confidence) && isa(value.probabilities, "double") && ...
    isequal(size(value.probabilities), [1, 8]) && ...
    all(isnan(value.probabilities)) && ...
    isa(value.inference_ms, "double") && ...
    isscalar(value.inference_ms) && isnan(value.inference_ms) && ...
    isa(value.round_trip_ms, "double") && ...
    isscalar(value.round_trip_ms) && isnan(value.round_trip_ms) && ...
    isa(value.sequence, "uint64") && isscalar(value.sequence) && ...
    value.sequence == uint64(0) && ...
    isa(value.sensor_time_s, "double") && ...
    isscalar(value.sensor_time_s) && isnan(value.sensor_time_s);
end

function valid = isBoundedDouble(value, minimum, maximum)
valid = isa(value, "double") && isscalar(value) && isreal(value) && ...
    isfinite(value) && value >= minimum && value <= maximum;
end

function valid = isTextMember(value, allowed)
valid = isTextScalar(value) && ismember(string(value), allowed);
end

function valid = isExactText(value, expected)
valid = isTextScalar(value) && string(value) == expected;
end

function valid = isTextScalar(value)
valid = (ischar(value) && isrow(value)) || ...
    (isstring(value) && isscalar(value) && ~ismissing(value));
end

function labels = recognitionClassLabels()
labels = ["REST", "WRIST_UP", "WRIST_DOWN", "FOREARM_IN", ...
    "FOREARM_OUT", "ARM_UP", "ARM_DOWN", "FIST"];
end
