function state = ads1298_emg_filter_create(sampleRateHz, channelCount)
%ADS1298_EMG_FILTER_CREATE Create a stateful causal EMG filter cascade.

if ~isnumeric(sampleRateHz) || ~isscalar(sampleRateHz) || ...
        ~isreal(sampleRateHz) || ~isfinite(sampleRateHz) || sampleRateHz <= 480
    error("ads1298_emg_filter_create:InvalidSampleRate", ...
        "sampleRateHz must be a finite scalar greater than 480 Hz.");
end
if ~isnumeric(channelCount) || ~isscalar(channelCount) || ...
        ~isreal(channelCount) || ~isfinite(channelCount) || ...
        channelCount < 1 || channelCount ~= fix(channelCount)
    error("ads1298_emg_filter_create:InvalidChannelCount", ...
        "channelCount must be a positive integer.");
end

requiredFunctions = ["butter", "iirnotch", "filtic"];
for functionName = requiredFunctions
    if exist(functionName, "file") ~= 2
        error("ads1298_emg_filter_create:MissingSignalProcessingToolbox", ...
            "Required Signal Processing Toolbox function %s is unavailable.", ...
            functionName);
    end
end

nyquistHz = sampleRateHz / 2;
[highpassB, highpassA] = butter(4, 20 / nyquistHz, "high");
mainsCenter = 50 / nyquistHz;
mainsBandwidth = 4 / nyquistHz;
[mainsBandstopB, mainsBandstopA] = iirnotch( ...
    mainsCenter, mainsBandwidth);
harmonicCenter = 150 / nyquistHz;
[harmonicNotchB, harmonicNotchA] = iirnotch( ...
    harmonicCenter, 4 / nyquistHz);
[lowpassB, lowpassA] = butter(4, 240 / nyquistHz, "low");

state = struct( ...
    "sampleRateHz", double(sampleRateHz), ...
    "channelCount", double(channelCount), ...
    "initialized", false, ...
    "highpassB", highpassB, ...
    "highpassA", highpassA, ...
    "mainsBandstopB", mainsBandstopB, ...
    "mainsBandstopA", mainsBandstopA, ...
    "harmonicNotchB", harmonicNotchB, ...
    "harmonicNotchA", harmonicNotchA, ...
    "lowpassB", lowpassB, ...
    "lowpassA", lowpassA, ...
    "highpassZi", zeros(filterOrder(highpassB, highpassA), channelCount), ...
    "mainsBandstopZi", zeros( ...
        filterOrder(mainsBandstopB, mainsBandstopA), channelCount), ...
    "harmonicNotchZi", zeros( ...
        filterOrder(harmonicNotchB, harmonicNotchA), channelCount), ...
    "lowpassZi", zeros( ...
        filterOrder(lowpassB, lowpassA), channelCount));
end

function order = filterOrder(numerator, denominator)
order = max(numel(numerator), numel(denominator)) - 1;
end
