function state = gesture_protocol_start(protocol)
state = struct( ...
    "protocol", protocol, ...
    "trialQueue", protocol.trialTable, ...
    "currentTrialIndex", 1, ...
    "currentStageIndex", 1, ...
    "stageStartTime", 0, ...
    "lastTime", -Inf, ...
    "started", false, ...
    "finished", false, ...
    "stopped", false, ...
    "invalidTrialIds", zeros(0, 1), ...
    "lastBreakBlock", 0);
end
