function session = gesture_session_create(config, protocol)
requiredFields = ["CaptureDirectory", "SubjectId", "SessionId", ...
    "ArmSide", "OperatorCode", "SleeveSize", "DeviceIdentifier", ...
    "ElectrodeLayoutVersion", "PcbOrientationVersion"];
if ~isstruct(config) || ~isscalar(config) || ...
        ~all(isfield(config, requiredFields))
    error("gesture_session_create:InvalidConfig", ...
        "config must contain every required session field.");
end

captureDirectory = requiredText(config.CaptureDirectory, "CaptureDirectory");
if ~isfolder(captureDirectory)
    error("gesture_session_create:InvalidConfig", ...
        "CaptureDirectory must be an existing directory.");
end
subjectId = requiredText(config.SubjectId, "SubjectId");
sessionId = requiredText(config.SessionId, "SessionId");
armSide = requiredText(config.ArmSide, "ArmSide");
operatorCode = requiredText(config.OperatorCode, "OperatorCode");
sleeveSize = requiredText(config.SleeveSize, "SleeveSize");
deviceIdentifier = requiredText(config.DeviceIdentifier, "DeviceIdentifier");
layoutVersion = requiredText(config.ElectrodeLayoutVersion, ...
    "ElectrodeLayoutVersion");
orientationVersion = requiredText(config.PcbOrientationVersion, ...
    "PcbOrientationVersion");

if isempty(regexp(subjectId, "^S\d{3}$", "once"))
    error("gesture_session_create:InvalidSubjectId", ...
        "SubjectId must use the pseudonymous S### format.");
end
tokens = regexp(sessionId, "^(S\d{3})_D\d{2}_R\d{2}$", ...
    "tokens", "once");
if isempty(tokens)
    error("gesture_session_create:InvalidSessionId", ...
        "SessionId must use the S###_D##_R## format.");
end
if subjectId ~= string(tokens{1})
    error("gesture_session_create:SessionSubjectMismatch", ...
        "The SubjectId embedded in SessionId must match SubjectId.");
end
if armSide ~= "left"
    error("gesture_session_create:ArmNotAllowed", ...
        "Only the left arm is permitted by this acquisition protocol.");
end
validateProtocol(protocol);

session = struct( ...
    "base", sessionId, ...
    "rawPath", fullfile(captureDirectory, sessionId + "_raw.csv"), ...
    "filteredPath", fullfile(captureDirectory, sessionId + "_filtered.csv"), ...
    "imuPath", fullfile(captureDirectory, sessionId + "_imu.csv"), ...
    "eventsPath", fullfile(captureDirectory, sessionId + "_events.csv"), ...
    "metadataPath", fullfile(captureDirectory, sessionId + "_metadata.json"), ...
    "qualityPath", fullfile(captureDirectory, sessionId + "_quality.json"));

artifactPaths = [session.rawPath, session.filteredPath, session.imuPath, ...
    session.eventsPath, session.metadataPath, session.qualityPath];
if any(isfile(artifactPaths) | isfolder(artifactPaths))
    error("gesture_session_create:OutputExists", ...
        "One or more proposed session artifact paths already exist.");
end

metadata = struct( ...
    "subject_id", subjectId, ...
    "session_id", sessionId, ...
    "arm_side", armSide, ...
    "operator_code", operatorCode, ...
    "sleeve_size", sleeveSize, ...
    "device_identifier", deviceIdentifier, ...
    "protocol_version", string(protocol.version), ...
    "protocol_seed", double(protocol.seed), ...
    "block_count", double(protocol.blockCount), ...
    "trial_table", protocol.trialTable, ...
    "created_at_utc", string(datetime("now", "TimeZone", "UTC", ...
        "Format", "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'")), ...
    "emg_rate_hz", 500, ...
    "imu_rate_hz", 104, ...
    "ads1298_gain", 6, ...
    "accelerometer_range_g", 4, ...
    "gyroscope_range_dps", 500, ...
    "electrode_layout_version", layoutVersion, ...
    "pcb_orientation_version", orientationVersion, ...
    "acquisition_software_version", "guided_acquisition_v1", ...
    "matlab_version", string(version), ...
    "completed", false, ...
    "stopped_by_operator", false, ...
    "terminal_status", "created");
session.metadata = metadata;

gesture_internal.write_session_metadata(session.metadataPath, metadata);
writetable(emptyEvents(), session.eventsPath, Encoding="UTF-8");
end

function value = requiredText(value, fieldName)
if ~(ischar(value) || (isstring(value) && isscalar(value)))
    error("gesture_session_create:InvalidConfig", ...
        "%s must be a nonempty text scalar.", fieldName);
end
value = string(value);
if strlength(strtrim(value)) == 0
    error("gesture_session_create:InvalidConfig", ...
        "%s must be a nonempty text scalar.", fieldName);
end
end

function validateProtocol(protocol)
requiredFields = ["version", "seed", "blockCount", "trialTable"];
if ~isstruct(protocol) || ~isscalar(protocol) || ...
        ~all(isfield(protocol, requiredFields)) || ~istable(protocol.trialTable)
    error("gesture_session_create:InvalidProtocol", ...
        "protocol must contain version, seed, blockCount, and trialTable.");
end
end

function events = emptyEvents()
events = table(zeros(0,1), strings(0,1), zeros(0,1), zeros(0,1), ...
    strings(0,1), false(0,1), strings(0,1), 'VariableNames', ...
    {'session_time_s','event_type','block_id','trial_id', ...
     'gesture_id','valid','note'});
end
