function protocol = gesture_protocol_create(seed, blockCount)
if nargin < 2, blockCount = 2; end
if ~isnumeric(seed) || ~isscalar(seed) || ~isreal(seed) || ~isfinite(seed) || ...
        seed < 0 || seed ~= fix(seed)
    error("gesture_protocol_create:InvalidSeed", ...
        "seed must be a nonnegative integer scalar.");
end
if ~isnumeric(blockCount) || ~isscalar(blockCount) || ~isreal(blockCount) || ...
        ~isfinite(blockCount) || blockCount ~= 2
    error("gesture_protocol_create:InvalidBlockCount", ...
        "blockCount must equal 2 for eight_pose_v5.");
end

targets = ["WRIST_UP", "WRIST_DOWN", "FOREARM_IN", ...
    "FOREARM_OUT", "ARM_UP", "ARM_DOWN", "FIST"];
stream = RandStream("mt19937ar", "Seed", double(seed));
trialId = (1:(blockCount * numel(targets))).';
blockId = repelem((1:blockCount).', numel(targets), 1);
gestureId = strings(size(trialId));
row = 1;
for block = 1:blockCount
    order = randperm(stream, numel(targets));
    gestureId(row:row + numel(targets) - 1) = targets(order).';
    row = row + numel(targets);
end

protocol = struct( ...
    "version", "eight_pose_v5", ...
    "seed", double(seed), ...
    "blockCount", 2, ...
    "classLabels", ["REST", targets], ...
    "targetLabels", targets, ...
    "stageNames", ["baseline", "prepare", "movement", ...
        "target_hold", "return", "recovery"], ...
    "stageDurationsSeconds", [2, 1, 1.5, 4, 2, 2], ...
    "guardSeconds", 0.4, ...
    "breakEveryBlocks", 0, ...
    "breakDurationSeconds", 0, ...
    "breakAfterBlocks", zeros(1, 0), ...
    "trialTable", table(trialId, blockId, gestureId, ...
        false(size(trialId)), 'VariableNames', ...
        {'trial_id', 'block_id', 'gesture_id', 'is_repeat'}));
end
