function gesture_append_events(eventsPath, events)
if ~(ischar(eventsPath) || (isstring(eventsPath) && isscalar(eventsPath))) || ...
        ~isfile(eventsPath)
    error("gesture_append_events:InvalidEvents", ...
        "eventsPath must name an existing event CSV file.");
end
validateEvents(events);
validatePersistedHeader(eventsPath);
if isempty(events)
    return;
end

persisted = readtable(eventsPath, TextType="string");
if ~isempty(persisted)
    lastTime = double(persisted.session_time_s(end));
    if double(events.session_time_s(1)) < lastTime
        error("gesture_append_events:NonmonotonicTime", ...
            "Event times must not precede the last persisted event.");
    end
end
writetable(events, eventsPath, WriteMode="append", ...
    WriteVariableNames=false, Encoding="UTF-8");
end

function validateEvents(events)
schema = ["session_time_s", "event_type", "block_id", "trial_id", ...
    "gesture_id", "valid", "note"];
if ~istable(events) || ~isequal(string(events.Properties.VariableNames), schema)
    error("gesture_append_events:InvalidEvents", ...
        "events must use the required ordered event schema.");
end
if ~isSingleColumn(events.session_time_s, height(events)) || ...
        ~isfloat(events.session_time_s) || ~isreal(events.session_time_s) || ...
        any(~isfinite(events.session_time_s)) || any(events.session_time_s < 0)
    error("gesture_append_events:InvalidEvents", ...
        "session_time_s values must be finite and nonnegative.");
end
if ~isSingleColumn(events.event_type, height(events)) || ...
        ~isstring(events.event_type) || ...
        ~isSingleColumn(events.block_id, height(events)) || ...
        ~isnumeric(events.block_id) || ~isreal(events.block_id) || ...
        any(~isfinite(events.block_id)) || ...
        ~isSingleColumn(events.trial_id, height(events)) || ...
        ~isnumeric(events.trial_id) || ~isreal(events.trial_id) || ...
        any(~isfinite(events.trial_id)) || ...
        ~isSingleColumn(events.gesture_id, height(events)) || ...
        ~isstring(events.gesture_id) || ...
        ~isSingleColumn(events.valid, height(events)) || ...
        ~islogical(events.valid) || ...
        ~isSingleColumn(events.note, height(events)) || ~isstring(events.note)
    error("gesture_append_events:InvalidEvents", ...
        "events must use scalar-width variables of the required types.");
end
if any(diff(double(events.session_time_s)) < 0)
    error("gesture_append_events:NonmonotonicTime", ...
        "Event times must not move backwards.");
end
end

function validatePersistedHeader(eventsPath)
expectedHeader = 'session_time_s,event_type,block_id,trial_id,gesture_id,valid,note';
contents = fileread(eventsPath);
lineEnd = regexp(contents, '\r\n|\n|\r', 'once');
if isempty(lineEnd)
    header = contents;
else
    header = contents(1:lineEnd - 1);
end
if startsWith(header, char(65279))
    header = extractAfter(header, 1);
end
if ~strcmp(header, expectedHeader)
    error("gesture_append_events:InvalidEvents", ...
        "The persisted event CSV must use the required exact header.");
end
end

function tf = isSingleColumn(value, expectedRows)
tf = ismatrix(value) && size(value, 1) == expectedRows && ...
    size(value, 2) == 1;
end
